version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Generating the db dump...
      - touch dump_file.bz2
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
    files: dump_file.bz2
